### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by 5XS** [CrazorTheCat/BSDS-V40#10]
python Core.py start socket. But I can't login. And have this errors:

PS Z:\BSDS-V40-master\BSDS-V40> python ContentUpdater/Updater.py
Traceback (most recent call last):
  File "Z:\BSDS-V40-master\BSDS-V40\ContentUpdater\Updater.py", line 17, in <module>
    lastVersionFile = open("lastversion.txt", "r").read()
FileNotFoundError: [Errno 2] No such file or directory: 'lastversion.txt'

PS Z:\BSDS-V40-master\BSDS-V40> python ContentUpdater/Server.py
Traceback (most recent call last):
  File "Z:\BSDS-V40-master\BSDS-V40\ContentUpdater\Server.py", line 8, in <module>
    os.chdir("Update")
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'Update'

**Comment by CrazorTheCat** [comment]
Linux is not support until v41 so if you are using a phone/tablet or a hosting service that use linux

**Comment by 5XS** [comment]
> Linux is not support until v41 so if you are using a phone/tablet or a hosting service that use linux

I'm using PC

**Comment by CrazorTheCat** [comment]
windows?

**Comment by 5XS** [comment]
yes

**Comment by CrazorTheCat** [comment]
uh weird well i will completly change v39 and v40 with the release of v41 so it will be fixed in coming updates
