### ISSUE TITLE
жжежка

### ISSUE THREAD

**Issue by pedikdev** [CrazorTheCat/BSDS-V40#2]
я твою mom в рот туда сюда понял
![java-schmiby](https://user-images.githubusercontent.com/85879842/143081493-966a4073-0272-4dfe-9f23-769d5d0d16d1.gif)

**Comment by CrazorTheCat** [comment]
nice man very constructive comment i mean if you have nothing better to say than this, just go away xD

**Comment by KittenPro** [comment]
Ладно
