### ISSUE TITLE
Лдлндншдрлднднлднлднлднлдш

### ISSUE THREAD

**Issue by KittenPro** [CrazorTheCat/BSDS-V40#3]
Ертеообтрльпрлнолноенлеглеглпотпртеронкнлкнлкрлгелгелполполпоьробрлбрлбнлбилноьоньпрлроьпрлгршьролнолооркрращропклщркплзркпщлрпрзлкпоз'рклрлщєпарлщєапаполщєнрктлжґкриіґдтлкрткрулзєукртощукнощукнолщєкцщкнцєонцкшщцгцтєшзнцкткнршщєцкнрвєтшзкррвтшзєкновтлщєвкнрлщґвкнонрвквкнрлщґвкнвкрлщґртлщґвкдвкртґнрктґощкрощґвкнтощґкерщєошреощрцтшщєншщтєкнртлщєиртлз'екткнлщєрєкриєлщрклтщнр'тлзеркерклшз'рикошз'кпикпрлщкєщшпркжжпгомпожщмтпщєлмоупшщєроупрєшщоупршщєпмтгєпщижтпущршжуащєрупх хмзїамїиапиїпиєпащшоиопаєлщтивпєро'чпзизшоапишзєоапиєошщвпрошщєупорщєпвогващєотпуалщєпопшщєрпщшоиєвпщлтилщєапрлщєупрлщєпртщєпвртлєщуползєрпуоилзєвпизвплєєиовплщєипащлєтпащлєтптоивплщтмвптлщєпщоагощєпауошщєпіаошщєпваощиєраиощвємощєвпмиощжвпиощжаиощжавоищємваощжимваощжрощжсвмидживмиолжаилжмиолвамидоєєпєиєвпвпєєвмщвпошщипвоєщивпжощтмпвощжимвпощижповащєптаужощпуаощємуаощєрукгщєкврпгщєукщцкгппщцкшпукпшщпукощґавлщопвалщґрвалщґроашщґпоґлщґкіптаплґтзвероєзвкорщлвпрєвплщопощєпорощєверлщєпвєщороощєвпрроощєверєощветоуруерттуерлщєерлщєукиурлщєєуерщєоекєугщеркпоєзеруопуивпєтлзвпиєвеєороз

**Comment by KittenPro** [comment]
GitHub тестирует баклажаны в жопе Python Developers! Как это скажется на пользователях???

**Comment by q3dd** [comment]
it is not a russian repo

**Comment by KittenPro** [comment]
> 

Мне похуй
